import MyAppBar from "./components/Appbar";
import { Providers } from "./provider";
import "./styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MyAppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
